name: cl_media_tools_example
description: "Demonstrates how to use the cl_media_tools plugin."
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cl_basic_types:
    path: ../../cl_basic_types
  flutter:
    sdk: flutter
  file_picker: ^10.0.0
  path: ^1.9.0
  cl_media_tools:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
